#!/bin/bash
set -e

year=$1
day=$2
input=$3

# Compile
g++ -std=c++17 -O2 "${year}/${day}.cpp" -o "${day}"

# Execute
start_time=$(date +%s%N);
"./${day}" < "${year}/inputs/${day}_${input}.in"
end_time=$(date +%s%N);

# Print 
elapsed_time=$(((end_time - start_time) / 1000000))
echo "Running took ${elapsed_time}ms"

# Cleanup
rm "./${day}";
